# @Author: Julie Keisler <jkeisler>
# @Date:   2023-10-11T10:38:00+02:00
# @Email:  julie.keisler.rfo@gmail.com
# @Project: Dragon
# @Last modified by:   jkeisler
# @Last modified time: 2023-10-11T10:38:00+02:00
# @License: CeCILL-C (http://www.cecill.info/index.fr.html)
# @Copyright: Copyright (C) 2023 Julie Keisler

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 1

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package
  system_packages: true

submodules:
  include:
    - Search_Space
    - Search_Algorithm
    - Dev_guide
    - Examples
    - Quickstart
    - Welcome
  recursive: true
