version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

formats:
   - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
    path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package
  system_packages: true

version: 2

submodules:
  include: all
  recursive: true
