version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

submodules:
  include:
    - Search_space
    - Search_algprithm
    - Examples
    - Quickstart
    - Toctree
    - Welcome
  recursive: true
