[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dragon"
authors = [{name = "Keisler", email = "julie.keisler.rfo@gmail.com"}]
dynamic = ["version", "description"]
